// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbh4pyGHUyCIvdsTUGHH-xwnWyrBkZfY',
    appId: '1:775550196522:android:8a459944a856dc4756dc53',
    messagingSenderId: '775550196522',
    projectId: 'swiftcart-77608',
    databaseURL: 'https://swiftcart-77608-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftcart-77608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIff3HutJzk9sRyZe7OrZDB7n4-oLoVuQ',
    appId: '1:775550196522:ios:31c9d181c5c5efcb56dc53',
    messagingSenderId: '775550196522',
    projectId: 'swiftcart-77608',
    databaseURL: 'https://swiftcart-77608-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftcart-77608.firebasestorage.app',
    iosClientId: '775550196522-qg6d1380pmjt9udgfnfb7m0bu85obk8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftcart',
  );
}
